// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eojsfxgzvxvftnmabnre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvanNmeGd6dnh2ZnRubWFibnJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNjY5NTgsImV4cCI6MjA3OTc0Mjk1OH0.-VD6BYdJYKIqCpewGoeUM77UX5Q73AFOa5CrBG6JBAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});